In [2]:
# Q1
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])

[5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3],
                   [2, 4, 5],
                   [1, 2, 3]])

print(array1.flatten())
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [4]:
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[1, 2],
                 [3, 4]])

print(arr1 == arr2)
print(np.array_equal(arr1, arr2))

[[ True  True]
 [ True  True]]
True


In [6]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

max_count = counts.max()
most_frequent = values[counts == max_count]

print("Most frequent value:", most_frequent)
print("Indices:", np.where(np.isin(x, most_frequent))[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = counts.max()
most_frequent = values[counts == max_count]

print("Most frequent values:", most_frequent)
print("Indices:", np.where(np.isin(y, most_frequent))[0])

Most frequent value: [1]
Indices: [0 5 7 8 9]
Most frequent values: [1 3]
Indices: [0 1 2 4 8 9]


In [7]:
g = np.matrix([[4, 1, 9],
              [12, 3, 1],
              [4, 5, 6]])

print("Sum of all elements:", np.sum(g))
print("Row-wise sum:", np.sum(g, axis=1))
print("Column-wise sum:", np.sum(g, axis=0))

Sum of all elements: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [8]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

print("Sum of diagonal elements:", np.trace(n_array))

eigenvalues, eigenvectors = np.linalg.eig(n_array)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

print("Inverse:")
print(np.linalg.inv(n_array))

print("Determinant:")
print(np.linalg.det(n_array))

Sum of diagonal elements: 176
Eigenvalues:
[28.097044  +0.j 49.73460452+0.j 98.16835147+0.j]
Eigenvectors:
[[-0.34637121+0.j  0.15017693+0.j  0.4574917 +0.j]
 [ 0.72784061+0.j  0.4852124 +0.j  0.28447814+0.j]
 [-0.59184038+0.j -0.8614034 +0.j  0.84248058+0.j]]
Inverse:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:
137180.0000000001


In [12]:
p = np.array([[1, 2],
              [2, 3]])

q = np.array([[4, 5],
              [6, 7]])
print(np.matmul(p, q))
print(np.cov(p, q))

p = np.array([[1, 2],
              [2, 3],
              [4, 5]])

q = np.array([[4, 5],
              [6, 7]])

print(np.matmul(p, q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19]
 [26 31]
 [46 55]]


In [14]:
from itertools import product
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
cartesian = list(product(x.flatten(), y.flatten()))

print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[(np.int32(2), np.int32(1)), (np.int32(2), np.int32(5)), (np.int32(2), np.int32(0)), (np.int32(2), np.int32(5)), (np.int32(2), np.int32(10)), (np.int32(2), np.int32(3)), (np.int32(3), np.int32(1)), (np.int32(3), np.int32(5)), (np.int32(3), np.int32(0)), (np.int32(3), np.int32(5)), (np.int32(3), np.int32(10)), (np.int32(3), np.int32(3)), (np.int32(4), np.int32(1)), (np.int32(4), np.int32(5)), (np.int32(4), np.int32(0)), (np.int32(4), np.int32(5)), (np.int32(4), np.int32(10)), (np.int32(4), np.int32(3)), (np.int32(3), np.int32(1)), (np.int32(3), np.int32(5)), (np.int32(3), np.int32(0)), (np.int32(3), np.int32(5)), (np.int32(3), np.int32(10)), (np.int32(3), np.int32(3)), (np.int32(2), np.int32(1)), (np.int32(2), np.int32(5)), (np.int32(2), np.int32(0)), (np.int32(2), np.int32(5)), (np.int32(2), np.int32(10)), (np.int32(2), np.int32(3)), (np.int3

In [15]:
# Q2
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
print(np.abs(array))
print(np.percentile(array, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard deviation:", np.std(array))
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard deviation:", np.std(array, axis=0))
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard deviation:", np.std(array, axis=1))

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean: -0.5
Median: -0.5
Standard deviation: 3.8622100754188224
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard deviation: [2.5 3.5 4.5]
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard deviation: [2.05480467 4.78423336]


In [16]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [17]:
# Q3
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [18]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array == array.astype(int)]
print(integer_elements)
float_elements = array[array != array.astype(int)]
print(float_elements)

[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
# Q4
import numpy as np
from PIL import Image
import os

def img_to_array(path):
    img = Image.open(path)

    if img.mode == "RGB":
        arr = np.array(img)
        output_path = os.path.splitext(path)[0] + "_rgb.txt"

        with open(output_path, "w") as f:
            f.write(f"# shape: {arr.shape[0]} {arr.shape[1]} {arr.shape[2]}\n")
            np.savetxt(f, arr.reshape(-1, 3), fmt="%d")

    else:
        img = img.convert("L")
        arr = np.array(img)
        output_path = os.path.splitext(path)[0] + "_gray.txt"

        with open(output_path, "w") as f:
            f.write(f"# shape: {arr.shape[0]} {arr.shape[1]}\n")
            np.savetxt(f, arr, fmt="%d")

    print("Saved:", output_path)
img_to_array("image.jpg")
img_to_array("gray_image.jpg")

In [ ]:
import numpy as np

def load_array(path):
    with open(path, "r") as f:
        header = f.readline().strip()

    shape = tuple(map(int, header.replace("# shape:", "").split()))

    arr = np.loadtxt(path)

    return arr.reshape(shape)
arr = load_array("image_rgb.txt")

print(arr.shape)
print(arr)